[project]
name = "python-stripe-test"
version = "0.1.0"
description = ""
authors = [
    {name = "V-tito",email = "0titovavv@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.1,<7.0)",
    "stripe (>=15.5.0,<16.0.0)",
    "psycopg (>=3.3.4,<4.0.0)",
    "psycopg-binary (>=3.3.4,<4.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry]
name = "python-stripe-test"
version = "0.1.0"
description = ""
authors = [
    "V-tito <0titovavv@gmail.com>"
]
readme = "README.md"
[tool.poetry.dependencies]
python=">=3.12"
    django=">=6.1,<7.0"
    stripe=">=15.5.0,<16.0.0"
    psycopg=">=3.3.4,<4.0.0"
    psycopg-binary=">=3.3.4,<4.0.0"
    python-dotenv =">=1.2.2,<2.0.0"
dj-database-url = "^3.1.2"
